name: datagov
dependencies:
  - python=3.5
  - pandas
  - matplotlib
  - numpy
  - requests
  - shapely
  - scipy
  - pysal
  - pip:
    - geopandas
    - ipyleaflet
    - folium
    - ckanapi
    - aiohttp
